const businessCategory = [
    "Accounting Services",
    "Accupuncture & Accupressure",
    "Administrative Services",
    "Advertising & Marketing (Other)",
    "Agriculturists & Agronomist",
    "Alternative Wellness (Products)",
    "Aluminium Profiles",
    "Animals (Other)",
    "Aquarium/Fish",
    "Art & Entertainment (Other)",
    "Art Dealer/Gallery Owner",
    "Artist",
    "Asset Finance",
    "Astrologer/ Astrologist/ Numerologists/ Palmist",
    "Auditor (Chartered Accountants)",
    "Auto Glass",
    "Auto/Car Body Shop/ Repair",
    "Auto/Car Parts & Accessories",
    "Auto/Car Rental/Leasing",
    "Auto/Car Sales",
    "Bakeries",
    "Books & Publication Reseller",
    "Bricklayer/Stonemason",
    "Builder/General Contractor",
    "Building Materials Reseller",
    "Bulk SMS, WhatsApp & Email Reseller",
    "Business Advisor/ Consultant",
    "Business Financing",
    "Business License Consultancy",
    "Business Loan",
    "Buying Agent",
    "CCTV & Other Security Survillance",
    "Car & Motorcycle (Other)",
    "Carpenter",
    "Carpet- Upholstery Cleaner",
    "Caterer",
    "Cement/Concrete Reseller",
    "Chemical Products",
    "Child Specialists/ Paediatrics",
    "Chiropractor",
    "Chocolatier",
    "Cleaning Products",
    "Cleaning Service",
    "Clothing Accessories Retailer",
    "Cloud Kitchen",
    "Cloud Services (Data & Digital)",
    "Commercial Vehicle Dealers",
    "Company Secretary",
    "Computer Repairs & Accessories",
    "Computer Training",
    "Consumer Loan",
    "Copywriter/ Content Writer",
    "Corporate Events",
    "Corporate Gifting",
    "Corrugated Boxes",
    "Cosmetics/Skin Care",
    "Counselor/Psychotherapist",
    "Courier",
    "Dance School/ Classes/ Trainer/ Professional Dancer",
    "Data Security & Recovery",
    "Demolition Contractor",
    "Dentist/ Orthodontist/ Dental Clinic",
    "Diamonds- Gold Jewellers",
    "Digital Coach/ Trainer",
    "Disc Jockey (DJ)",
    "Doctor/Physician",
    "Dog Trainer",
    "Dry Cleaning/Laundry (Personal)",
    "Dry Fruits & Exotic Fruits Seller",
    "ENT Practitioner/ Doctor",
    "ERP Software (Reseller)",
    "Eating Joints including Shakes & Juice Parlour",
    "Ecommerce Portal Management",
    "Education Counselling/ Admission Consultant",
    "Education Services/ Classes",
    "Electrical Accessories & Hardware",
    "Electrical Contractor",
    "Electrical Equipment Manufacture",
    "Electrical Products Dealers (Switches- Boards- Sockets)",
    "Electrical Tools & Equipments",
    "Electrician - Commercial",
    "Electricity & Gas Dealers",
    "Electronics Retailer",
    "Elevators",
    "Embroidery",
    "Employment/Labor Law Compliance",
    "Energy Consulting",
    "Environmental Products/ Services",
    "Event Rentals",
    "Event Venue/Room Rental",
    "Factory License Consultancy",
    "Fences & Area Security (Civil)",
    "Feng Shui- Tarot card",
    "Fine/ Fashion/ Imitation Jewelry",
    "Fire Protection",
    "Fireplace & Oven Builder",
    "Flooring Manufacture & Retail",
    "Flooring Services (Tile & Marble Mistri)",
    "Florist",
    "Food & Beverage (Other)",
    "Food Products (Reseller)",
    "Foreign Currency Exchange",
    "Funeral Planning/Services",
    "Furniture Manufacturer & Retailer",
    "Furniture Repair/Upholstery",
    "Garage Doors",
    "General Insurance",
    "Glass",
    "Graphic Designer & Digital Marketing",
    "Grooming (Look Enhancement)",
    "HVAC - Heating & Air",
    "Hair Color & Style Consultant",
    "Handmade Giftings including Paintings",
    "Hardware & Architectural Fittings",
    "Health & Wellness Products",
    "Health & Wellness Services",
    "Health Coach (Personalised Home Service)",
    "Health Facility/Gym/Club",
    "Health Insurance",
    "Hearing/Audiology",
    "Home Appliance Sales & Service",
    "Home Furnishings",
    "Hotel- Resort & Lodge",
    "Housing Loan & Education Loan",
    "Hypnotherapist",
    "IT & Networks",
    "Immigration Law",
    "In-Home Care",
    "Individual Leadership Coach",
    "Insolvency Practitioner",
    "Intellectual Property Law",
    "Investigative Services/Detective",
    "Jute Bags and Jute Products",
    "Kitchen Construction",
    "Lab Grown Diamond Jewellers",
    "Landscape Services",
    "Language Learning Centre",
    "Lawyer",
    "Leather Products",
    "Legal & Accounting (Other)",
    "Life Insurance - Aditya Birla",
    "Life Insurance - HDFC",
    "Life Insurance - LIC",
    "Life Insurance - TATA AIA",
    "Lighting Manufacture & Reseller",
    "MSME Loan & CGTMSE",
    "Machinery & Equipment Manufacture",
    "Machinery & Equipment Repair",
    "Magnetic Health Products",
    "Marbles- Granites & Tiles",
    "Martial Arts & Other Self Defence Training",
    "Massage Therapist",
    "Media Services (Print & TV/ News)",
    "Mediator/ Liasoning Agent",
    "Medical Furniture (Chairs- Beds- Tables- Creches)",
    "Medical Services (Others)",
    "Metal Fabrication",
    "Metal Work including Iron Grills",
    "Mobile & Telecommunication Products",
    "Moving Company",
    "Musicians",
    "Mutual Fund & SIP",
    "Naturopaths",
    "Non Metallic Minerals",
    "Non-Profits/Fundraising Organizations",
    "Nursery- Plantation & Tree Services",
    "Nutritional Supplements",
    "Occupational Safety",
    "Office Equipment/Machines",
    "Office Supplies & Stationeries",
    "Offshore Company Set up",
    "Optician",
    "Orthopaedics",
    "Outdoor Furniture",
    "Paint Manufacture & Reseller",
    "Painter/ Painting Mistri",
    "Paper & Paper Products",
    "Paper Bags & Plastic Bags",
    "Passport & Visa Services",
    "Pathology Lab/ Testing Centre/ Diagnostic Centre",
    "Payroll Service",
    "Personal Services (Other)",
    "Personal Trainer - Fitness",
    "Pest Control & Fumigation",
    "Pet Foods",
    "Pharmaceuticals (Manufacturer)",
    "Pharmacist & Pharmacy Store",
    "Photographer - Commercial",
    "Photographer - Personal (person)",
    "Plumbing- Swerage & Sanitation Services",
    "Pooja Store & Reseller of Idols/ Statue Deity",
    "Pools- Spas & Saunas",
    "Power Generator & Emergency Power Supply",
    "Pranic Healer/ Healing",
    "Pranic Healing",
    "Printer - Digital",
    "Printer - Large Format",
    "Printer - Offset",
    "Private Tutions/ Coaching",
    "Public Relation",
    "Real Estate Development",
    "Real Estate Maintenance/Care Taker",
    "Real Estate Planning Consultant",
    "Recruiter",
    "Residential Mortgages",
    "Restaurant- Bars & Cafes",
    "Restoration",
    "Road Freight Service/ Logistics",
    "Roofing & Gutters",
    "Rubber & Plastic",
    "Salon/Spa",
    "Security (Other)",
    "Security Personnel",
    "Senior Citizen Service Provider",
    "Septic Systems",
    "Shutters & Awnings",
    "Signage & Display Board",
    "Silver & Silver Products",
    "Social Event Manager/Planner",
    "Software & Mobile Application Developer",
    "Software Reseller (Antivirus- Tally- etc.)",
    "Solar Systsem & Solar Products",
    "Sophrologist",
    "Special Furniture",
    "Special Vehicle Transportation",
    "Sports & Leisure (Other)",
    "Sports Product/ Equipment Retailer",
    "Stock Broker",
    "Surveyor",
    "Tarot Card Reader",
    "Taxation Consultant",
    "Textiles & Fabric Reseller",
    "Tire Sales/Replacement",
    "Tours Travels & Ticketing",
    "Training & Coaching (Other)",
    "Translator/Language Services",
    "Transport & Shipping (Other)",
    "Transportation Equipment",
    "Travel Guide & Services",
    "UPS/Inverter/ DG Set/ Power Supply",
    "Uniforms Manufacturer & Reseller",
    "Vastu Consultancy",
    "Veterinarian",
    "Videographer/Film Producer",
    "Virtual Assistant & Answering Machine/ Services",
    "Waste Disposal",
    "Water Systems",
    "Waterproofing-Weatherproofing",
    "Web Design & Development- SEO",
    "Window Cleaning",
    "Windows & Doors",
    "Wine Merchant/Wine Shop",
    "Wires & Cables",
    "Wood & Cork (except Furniture)",
    "Yoga/Pilates/Qi-gong Trainer"
];

export default businessCategory;